// Code generated by entc, DO NOT EDIT.

package officeroom

const (
	// Label holds the string label denoting the officeroom type in the database.
	Label = "officeroom"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoomnumber holds the string denoting the roomnumber field in the database.
	FieldRoomnumber = "roomnumber"

	// EdgeOfficeroom2doctorinfo holds the string denoting the officeroom2doctorinfo edge name in mutations.
	EdgeOfficeroom2doctorinfo = "officeroom2doctorinfo"

	// Table holds the table name of the officeroom in the database.
	Table = "officerooms"
	// Officeroom2doctorinfoTable is the table the holds the officeroom2doctorinfo relation/edge.
	Officeroom2doctorinfoTable = "doctorinfos"
	// Officeroom2doctorinfoInverseTable is the table name for the Doctorinfo entity.
	// It exists in this package in order to avoid circular dependency with the "doctorinfo" package.
	Officeroom2doctorinfoInverseTable = "doctorinfos"
	// Officeroom2doctorinfoColumn is the table column denoting the officeroom2doctorinfo relation/edge.
	Officeroom2doctorinfoColumn = "roomnumber"
)

// Columns holds all SQL columns for officeroom fields.
var Columns = []string{
	FieldID,
	FieldRoomnumber,
}

var (
	// RoomnumberValidator is a validator for the "roomnumber" field. It is called by the builders before save.
	RoomnumberValidator func(string) error
)
