// Code generated by entc, DO NOT EDIT.

package patientrights

const (
	// Label holds the string label denoting the patientrights type in the database.
	Label = "patientrights"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPermissionDate holds the string denoting the permissiondate field in the database.
	FieldPermissionDate = "permission_date"
	// FieldPermission holds the string denoting the permission field in the database.
	FieldPermission = "permission"
	// FieldPermissionArea holds the string denoting the permissionarea field in the database.
	FieldPermissionArea = "permission_area"
	// FieldResponsible holds the string denoting the responsible field in the database.
	FieldResponsible = "responsible"

	// EdgeEdgesOfPatientrightsAbilitypatientrights holds the string denoting the edgesofpatientrightsabilitypatientrights edge name in mutations.
	EdgeEdgesOfPatientrightsAbilitypatientrights = "EdgesOfPatientrightsAbilitypatientrights"
	// EdgeEdgesOfPatientrightsInsurance holds the string denoting the edgesofpatientrightsinsurance edge name in mutations.
	EdgeEdgesOfPatientrightsInsurance = "EdgesOfPatientrightsInsurance"
	// EdgeEdgesOfPatientrightsPatientrecord holds the string denoting the edgesofpatientrightspatientrecord edge name in mutations.
	EdgeEdgesOfPatientrightsPatientrecord = "EdgesOfPatientrightsPatientrecord"
	// EdgeEdgesOfPatientrightsMedicalrecordstaff holds the string denoting the edgesofpatientrightsmedicalrecordstaff edge name in mutations.
	EdgeEdgesOfPatientrightsMedicalrecordstaff = "EdgesOfPatientrightsMedicalrecordstaff"

	// Table holds the table name of the patientrights in the database.
	Table = "patientrights"
	// EdgesOfPatientrightsAbilitypatientrightsTable is the table the holds the EdgesOfPatientrightsAbilitypatientrights relation/edge.
	EdgesOfPatientrightsAbilitypatientrightsTable = "patientrights"
	// EdgesOfPatientrightsAbilitypatientrightsInverseTable is the table name for the Abilitypatientrights entity.
	// It exists in this package in order to avoid circular dependency with the "abilitypatientrights" package.
	EdgesOfPatientrightsAbilitypatientrightsInverseTable = "abilitypatientrights"
	// EdgesOfPatientrightsAbilitypatientrightsColumn is the table column denoting the EdgesOfPatientrightsAbilitypatientrights relation/edge.
	EdgesOfPatientrightsAbilitypatientrightsColumn = "Abilitypatientrights_id"
	// EdgesOfPatientrightsInsuranceTable is the table the holds the EdgesOfPatientrightsInsurance relation/edge.
	EdgesOfPatientrightsInsuranceTable = "patientrights"
	// EdgesOfPatientrightsInsuranceInverseTable is the table name for the Insurance entity.
	// It exists in this package in order to avoid circular dependency with the "insurance" package.
	EdgesOfPatientrightsInsuranceInverseTable = "insurances"
	// EdgesOfPatientrightsInsuranceColumn is the table column denoting the EdgesOfPatientrightsInsurance relation/edge.
	EdgesOfPatientrightsInsuranceColumn = "Insurance_id"
	// EdgesOfPatientrightsPatientrecordTable is the table the holds the EdgesOfPatientrightsPatientrecord relation/edge.
	EdgesOfPatientrightsPatientrecordTable = "patientrights"
	// EdgesOfPatientrightsPatientrecordInverseTable is the table name for the Patientrecord entity.
	// It exists in this package in order to avoid circular dependency with the "patientrecord" package.
	EdgesOfPatientrightsPatientrecordInverseTable = "patientrecords"
	// EdgesOfPatientrightsPatientrecordColumn is the table column denoting the EdgesOfPatientrightsPatientrecord relation/edge.
	EdgesOfPatientrightsPatientrecordColumn = "patientrecord_id"
	// EdgesOfPatientrightsMedicalrecordstaffTable is the table the holds the EdgesOfPatientrightsMedicalrecordstaff relation/edge.
	EdgesOfPatientrightsMedicalrecordstaffTable = "patientrights"
	// EdgesOfPatientrightsMedicalrecordstaffInverseTable is the table name for the Medicalrecordstaff entity.
	// It exists in this package in order to avoid circular dependency with the "medicalrecordstaff" package.
	EdgesOfPatientrightsMedicalrecordstaffInverseTable = "medicalrecordstaffs"
	// EdgesOfPatientrightsMedicalrecordstaffColumn is the table column denoting the EdgesOfPatientrightsMedicalrecordstaff relation/edge.
	EdgesOfPatientrightsMedicalrecordstaffColumn = "medicalrecordstaff_id"
)

// Columns holds all SQL columns for patientrights fields.
var Columns = []string{
	FieldID,
	FieldPermissionDate,
	FieldPermission,
	FieldPermissionArea,
	FieldResponsible,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Patientrights type.
var ForeignKeys = []string{
	"Abilitypatientrights_id",
	"Insurance_id",
	"medicalrecordstaff_id",
	"patientrecord_id",
}

var (
	// PermissionValidator is a validator for the "Permission" field. It is called by the builders before save.
	PermissionValidator func(string) error
	// PermissionAreaValidator is a validator for the "PermissionArea" field. It is called by the builders before save.
	PermissionAreaValidator func(string) error
	// ResponsibleValidator is a validator for the "Responsible" field. It is called by the builders before save.
	ResponsibleValidator func(string) error
)
