// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/theuo/app/ent/doctorinfo"
	"github.com/theuo/app/ent/educationlevel"
	"github.com/theuo/app/ent/predicate"
)

// EducationlevelUpdate is the builder for updating Educationlevel entities.
type EducationlevelUpdate struct {
	config
	hooks      []Hook
	mutation   *EducationlevelMutation
	predicates []predicate.Educationlevel
}

// Where adds a new predicate for the builder.
func (eu *EducationlevelUpdate) Where(ps ...predicate.Educationlevel) *EducationlevelUpdate {
	eu.predicates = append(eu.predicates, ps...)
	return eu
}

// SetLevel sets the level field.
func (eu *EducationlevelUpdate) SetLevel(s string) *EducationlevelUpdate {
	eu.mutation.SetLevel(s)
	return eu
}

// AddEducationlevel2doctorinfoIDs adds the educationlevel2doctorinfo edge to Doctorinfo by ids.
func (eu *EducationlevelUpdate) AddEducationlevel2doctorinfoIDs(ids ...int) *EducationlevelUpdate {
	eu.mutation.AddEducationlevel2doctorinfoIDs(ids...)
	return eu
}

// AddEducationlevel2doctorinfo adds the educationlevel2doctorinfo edges to Doctorinfo.
func (eu *EducationlevelUpdate) AddEducationlevel2doctorinfo(d ...*Doctorinfo) *EducationlevelUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return eu.AddEducationlevel2doctorinfoIDs(ids...)
}

// Mutation returns the EducationlevelMutation object of the builder.
func (eu *EducationlevelUpdate) Mutation() *EducationlevelMutation {
	return eu.mutation
}

// RemoveEducationlevel2doctorinfoIDs removes the educationlevel2doctorinfo edge to Doctorinfo by ids.
func (eu *EducationlevelUpdate) RemoveEducationlevel2doctorinfoIDs(ids ...int) *EducationlevelUpdate {
	eu.mutation.RemoveEducationlevel2doctorinfoIDs(ids...)
	return eu
}

// RemoveEducationlevel2doctorinfo removes educationlevel2doctorinfo edges to Doctorinfo.
func (eu *EducationlevelUpdate) RemoveEducationlevel2doctorinfo(d ...*Doctorinfo) *EducationlevelUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return eu.RemoveEducationlevel2doctorinfoIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (eu *EducationlevelUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := eu.mutation.Level(); ok {
		if err := educationlevel.LevelValidator(v); err != nil {
			return 0, &ValidationError{Name: "level", err: fmt.Errorf("ent: validator failed for field \"level\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EducationlevelMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EducationlevelUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EducationlevelUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EducationlevelUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eu *EducationlevelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   educationlevel.Table,
			Columns: educationlevel.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: educationlevel.FieldID,
			},
		},
	}
	if ps := eu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.Level(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: educationlevel.FieldLevel,
		})
	}
	if nodes := eu.mutation.RemovedEducationlevel2doctorinfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   educationlevel.Educationlevel2doctorinfoTable,
			Columns: []string{educationlevel.Educationlevel2doctorinfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctorinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.Educationlevel2doctorinfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   educationlevel.Educationlevel2doctorinfoTable,
			Columns: []string{educationlevel.Educationlevel2doctorinfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctorinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{educationlevel.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// EducationlevelUpdateOne is the builder for updating a single Educationlevel entity.
type EducationlevelUpdateOne struct {
	config
	hooks    []Hook
	mutation *EducationlevelMutation
}

// SetLevel sets the level field.
func (euo *EducationlevelUpdateOne) SetLevel(s string) *EducationlevelUpdateOne {
	euo.mutation.SetLevel(s)
	return euo
}

// AddEducationlevel2doctorinfoIDs adds the educationlevel2doctorinfo edge to Doctorinfo by ids.
func (euo *EducationlevelUpdateOne) AddEducationlevel2doctorinfoIDs(ids ...int) *EducationlevelUpdateOne {
	euo.mutation.AddEducationlevel2doctorinfoIDs(ids...)
	return euo
}

// AddEducationlevel2doctorinfo adds the educationlevel2doctorinfo edges to Doctorinfo.
func (euo *EducationlevelUpdateOne) AddEducationlevel2doctorinfo(d ...*Doctorinfo) *EducationlevelUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return euo.AddEducationlevel2doctorinfoIDs(ids...)
}

// Mutation returns the EducationlevelMutation object of the builder.
func (euo *EducationlevelUpdateOne) Mutation() *EducationlevelMutation {
	return euo.mutation
}

// RemoveEducationlevel2doctorinfoIDs removes the educationlevel2doctorinfo edge to Doctorinfo by ids.
func (euo *EducationlevelUpdateOne) RemoveEducationlevel2doctorinfoIDs(ids ...int) *EducationlevelUpdateOne {
	euo.mutation.RemoveEducationlevel2doctorinfoIDs(ids...)
	return euo
}

// RemoveEducationlevel2doctorinfo removes educationlevel2doctorinfo edges to Doctorinfo.
func (euo *EducationlevelUpdateOne) RemoveEducationlevel2doctorinfo(d ...*Doctorinfo) *EducationlevelUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return euo.RemoveEducationlevel2doctorinfoIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (euo *EducationlevelUpdateOne) Save(ctx context.Context) (*Educationlevel, error) {
	if v, ok := euo.mutation.Level(); ok {
		if err := educationlevel.LevelValidator(v); err != nil {
			return nil, &ValidationError{Name: "level", err: fmt.Errorf("ent: validator failed for field \"level\": %w", err)}
		}
	}

	var (
		err  error
		node *Educationlevel
	)
	if len(euo.hooks) == 0 {
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EducationlevelMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			mut = euo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, euo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EducationlevelUpdateOne) SaveX(ctx context.Context) *Educationlevel {
	e, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return e
}

// Exec executes the query on the entity.
func (euo *EducationlevelUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EducationlevelUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (euo *EducationlevelUpdateOne) sqlSave(ctx context.Context) (e *Educationlevel, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   educationlevel.Table,
			Columns: educationlevel.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: educationlevel.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Educationlevel.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := euo.mutation.Level(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: educationlevel.FieldLevel,
		})
	}
	if nodes := euo.mutation.RemovedEducationlevel2doctorinfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   educationlevel.Educationlevel2doctorinfoTable,
			Columns: []string{educationlevel.Educationlevel2doctorinfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctorinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.Educationlevel2doctorinfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   educationlevel.Educationlevel2doctorinfoTable,
			Columns: []string{educationlevel.Educationlevel2doctorinfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctorinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	e = &Educationlevel{config: euo.config}
	_spec.Assign = e.assignValues
	_spec.ScanValues = e.scanValues()
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{educationlevel.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return e, nil
}
