// Code generated by entc, DO NOT EDIT.

package unpaybill

const (
	// Label holds the string label denoting the unpaybill type in the database.
	Label = "unpaybill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"

	// EdgeEdgesOfTreatment holds the string denoting the edgesoftreatment edge name in mutations.
	EdgeEdgesOfTreatment = "EdgesOfTreatment"
	// EdgeEdgesOfBills holds the string denoting the edgesofbills edge name in mutations.
	EdgeEdgesOfBills = "EdgesOfBills"

	// Table holds the table name of the unpaybill in the database.
	Table = "unpaybills"
	// EdgesOfTreatmentTable is the table the holds the EdgesOfTreatment relation/edge.
	EdgesOfTreatmentTable = "unpaybills"
	// EdgesOfTreatmentInverseTable is the table name for the Treatment entity.
	// It exists in this package in order to avoid circular dependency with the "treatment" package.
	EdgesOfTreatmentInverseTable = "treatments"
	// EdgesOfTreatmentColumn is the table column denoting the EdgesOfTreatment relation/edge.
	EdgesOfTreatmentColumn = "treatment_id"
	// EdgesOfBillsTable is the table the holds the EdgesOfBills relation/edge.
	EdgesOfBillsTable = "bills"
	// EdgesOfBillsInverseTable is the table name for the Bill entity.
	// It exists in this package in order to avoid circular dependency with the "bill" package.
	EdgesOfBillsInverseTable = "bills"
	// EdgesOfBillsColumn is the table column denoting the EdgesOfBills relation/edge.
	EdgesOfBillsColumn = "treatment_id"
)

// Columns holds all SQL columns for unpaybill fields.
var Columns = []string{
	FieldID,
	FieldStatus,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Unpaybill type.
var ForeignKeys = []string{
	"treatment_id",
}

var (
	// StatusValidator is a validator for the "Status" field. It is called by the builders before save.
	StatusValidator func(string) error
)
