// Code generated by entc, DO NOT EDIT.

package paytype

const (
	// Label holds the string label denoting the paytype type in the database.
	Label = "paytype"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPaytype holds the string denoting the paytype field in the database.
	FieldPaytype = "paytype"

	// EdgeEdgesOfBills holds the string denoting the edgesofbills edge name in mutations.
	EdgeEdgesOfBills = "EdgesOfBills"

	// Table holds the table name of the paytype in the database.
	Table = "paytypes"
	// EdgesOfBillsTable is the table the holds the EdgesOfBills relation/edge.
	EdgesOfBillsTable = "bills"
	// EdgesOfBillsInverseTable is the table name for the Bill entity.
	// It exists in this package in order to avoid circular dependency with the "bill" package.
	EdgesOfBillsInverseTable = "bills"
	// EdgesOfBillsColumn is the table column denoting the EdgesOfBills relation/edge.
	EdgesOfBillsColumn = "paytype_id"
)

// Columns holds all SQL columns for paytype fields.
var Columns = []string{
	FieldID,
	FieldPaytype,
}

var (
	// PaytypeValidator is a validator for the "Paytype" field. It is called by the builders before save.
	PaytypeValidator func(string) error
)
