// Code generated by entc, DO NOT EDIT.

package gender

const (
	// Label holds the string label denoting the gender type in the database.
	Label = "gender"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGenderstatus holds the string denoting the genderstatus field in the database.
	FieldGenderstatus = "genderstatus"

	// EdgeEdgesOfPatientrecord holds the string denoting the edgesofpatientrecord edge name in mutations.
	EdgeEdgesOfPatientrecord = "EdgesOfPatientrecord"

	// Table holds the table name of the gender in the database.
	Table = "genders"
	// EdgesOfPatientrecordTable is the table the holds the EdgesOfPatientrecord relation/edge.
	EdgesOfPatientrecordTable = "patientrecords"
	// EdgesOfPatientrecordInverseTable is the table name for the Patientrecord entity.
	// It exists in this package in order to avoid circular dependency with the "patientrecord" package.
	EdgesOfPatientrecordInverseTable = "patientrecords"
	// EdgesOfPatientrecordColumn is the table column denoting the EdgesOfPatientrecord relation/edge.
	EdgesOfPatientrecordColumn = "gender_id"
)

// Columns holds all SQL columns for gender fields.
var Columns = []string{
	FieldID,
	FieldGenderstatus,
}
