// Code generated by entc, DO NOT EDIT.

package typetreatment

const (
	// Label holds the string label denoting the typetreatment type in the database.
	Label = "typetreatment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"

	// EdgeTreatment holds the string denoting the treatment edge name in mutations.
	EdgeTreatment = "treatment"

	// Table holds the table name of the typetreatment in the database.
	Table = "typetreatments"
	// TreatmentTable is the table the holds the treatment relation/edge.
	TreatmentTable = "treatments"
	// TreatmentInverseTable is the table name for the Treatment entity.
	// It exists in this package in order to avoid circular dependency with the "treatment" package.
	TreatmentInverseTable = "treatments"
	// TreatmentColumn is the table column denoting the treatment relation/edge.
	TreatmentColumn = "typetreatment_id"
)

// Columns holds all SQL columns for typetreatment fields.
var Columns = []string{
	FieldID,
	FieldType,
}

var (
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
)
