// Code generated by entc, DO NOT EDIT.

package bloodtype

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team10/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Bloodtype applies equality check predicate on the "bloodtype" field. It's identical to BloodtypeEQ.
func Bloodtype(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBloodtype), v))
	})
}

// BloodtypeEQ applies the EQ predicate on the "bloodtype" field.
func BloodtypeEQ(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBloodtype), v))
	})
}

// BloodtypeNEQ applies the NEQ predicate on the "bloodtype" field.
func BloodtypeNEQ(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldBloodtype), v))
	})
}

// BloodtypeIn applies the In predicate on the "bloodtype" field.
func BloodtypeIn(vs ...string) predicate.Bloodtype {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Bloodtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldBloodtype), v...))
	})
}

// BloodtypeNotIn applies the NotIn predicate on the "bloodtype" field.
func BloodtypeNotIn(vs ...string) predicate.Bloodtype {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Bloodtype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldBloodtype), v...))
	})
}

// BloodtypeGT applies the GT predicate on the "bloodtype" field.
func BloodtypeGT(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldBloodtype), v))
	})
}

// BloodtypeGTE applies the GTE predicate on the "bloodtype" field.
func BloodtypeGTE(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldBloodtype), v))
	})
}

// BloodtypeLT applies the LT predicate on the "bloodtype" field.
func BloodtypeLT(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldBloodtype), v))
	})
}

// BloodtypeLTE applies the LTE predicate on the "bloodtype" field.
func BloodtypeLTE(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldBloodtype), v))
	})
}

// BloodtypeContains applies the Contains predicate on the "bloodtype" field.
func BloodtypeContains(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldBloodtype), v))
	})
}

// BloodtypeHasPrefix applies the HasPrefix predicate on the "bloodtype" field.
func BloodtypeHasPrefix(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldBloodtype), v))
	})
}

// BloodtypeHasSuffix applies the HasSuffix predicate on the "bloodtype" field.
func BloodtypeHasSuffix(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldBloodtype), v))
	})
}

// BloodtypeEqualFold applies the EqualFold predicate on the "bloodtype" field.
func BloodtypeEqualFold(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldBloodtype), v))
	})
}

// BloodtypeContainsFold applies the ContainsFold predicate on the "bloodtype" field.
func BloodtypeContainsFold(v string) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldBloodtype), v))
	})
}

// HasEdgesOfPatientrecord applies the HasEdge predicate on the "EdgesOfPatientrecord" edge.
func HasEdgesOfPatientrecord() predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EdgesOfPatientrecordTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EdgesOfPatientrecordTable, EdgesOfPatientrecordColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEdgesOfPatientrecordWith applies the HasEdge predicate on the "EdgesOfPatientrecord" edge with a given conditions (other predicates).
func HasEdgesOfPatientrecordWith(preds ...predicate.Patientrecord) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EdgesOfPatientrecordInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EdgesOfPatientrecordTable, EdgesOfPatientrecordColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Bloodtype) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Bloodtype) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bloodtype) predicate.Bloodtype {
	return predicate.Bloodtype(func(s *sql.Selector) {
		p(s.Not())
	})
}
