/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPatientrightstype
 */
export interface ControllersPatientrightstype {
    /**
     * 
     * @type {number}
     * @memberof ControllersPatientrightstype
     */
    abilitypatientrights?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersPatientrightstype
     */
    permission?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersPatientrightstype
     */
    permissionArea?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersPatientrightstype
     */
    responsible?: string;
}

export function ControllersPatientrightstypeFromJSON(json: any): ControllersPatientrightstype {
    return ControllersPatientrightstypeFromJSONTyped(json, false);
}

export function ControllersPatientrightstypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPatientrightstype {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'abilitypatientrights': !exists(json, 'abilitypatientrights') ? undefined : json['abilitypatientrights'],
        'permission': !exists(json, 'permission') ? undefined : json['permission'],
        'permissionArea': !exists(json, 'permissionArea') ? undefined : json['permissionArea'],
        'responsible': !exists(json, 'responsible') ? undefined : json['responsible'],
    };
}

export function ControllersPatientrightstypeToJSON(value?: ControllersPatientrightstype | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'abilitypatientrights': value.abilitypatientrights,
        'permission': value.permission,
        'permissionArea': value.permissionArea,
        'responsible': value.responsible,
    };
}


