/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersBill
 */
export interface ControllersBill {
    /**
     * 
     * @type {string}
     * @memberof ControllersBill
     */
    amount?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersBill
     */
    financier?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBill
     */
    paytype?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBill
     */
    unpaybill?: number;
}

export function ControllersBillFromJSON(json: any): ControllersBill {
    return ControllersBillFromJSONTyped(json, false);
}

export function ControllersBillFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersBill {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'financier': !exists(json, 'financier') ? undefined : json['financier'],
        'paytype': !exists(json, 'paytype') ? undefined : json['paytype'],
        'unpaybill': !exists(json, 'unpaybill') ? undefined : json['unpaybill'],
    };
}

export function ControllersBillToJSON(value?: ControllersBill | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'financier': value.financier,
        'paytype': value.paytype,
        'unpaybill': value.unpaybill,
    };
}


