/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersDoctorinfo
 */
export interface ControllersDoctorinfo {
    /**
     * 
     * @type {number}
     * @memberof ControllersDoctorinfo
     */
    department?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersDoctorinfo
     */
    doctorname?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersDoctorinfo
     */
    doctorsurname?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersDoctorinfo
     */
    educationlevel?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersDoctorinfo
     */
    licensenumber?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersDoctorinfo
     */
    officeroom?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDoctorinfo
     */
    prename?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDoctorinfo
     */
    registrar?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersDoctorinfo
     */
    telephonenumber?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersDoctorinfo
     */
    user?: number;
}

export function ControllersDoctorinfoFromJSON(json: any): ControllersDoctorinfo {
    return ControllersDoctorinfoFromJSONTyped(json, false);
}

export function ControllersDoctorinfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersDoctorinfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'department': !exists(json, 'department') ? undefined : json['department'],
        'doctorname': !exists(json, 'doctorname') ? undefined : json['doctorname'],
        'doctorsurname': !exists(json, 'doctorsurname') ? undefined : json['doctorsurname'],
        'educationlevel': !exists(json, 'educationlevel') ? undefined : json['educationlevel'],
        'licensenumber': !exists(json, 'licensenumber') ? undefined : json['licensenumber'],
        'officeroom': !exists(json, 'officeroom') ? undefined : json['officeroom'],
        'prename': !exists(json, 'prename') ? undefined : json['prename'],
        'registrar': !exists(json, 'registrar') ? undefined : json['registrar'],
        'telephonenumber': !exists(json, 'telephonenumber') ? undefined : json['telephonenumber'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function ControllersDoctorinfoToJSON(value?: ControllersDoctorinfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'department': value.department,
        'doctorname': value.doctorname,
        'doctorsurname': value.doctorsurname,
        'educationlevel': value.educationlevel,
        'licensenumber': value.licensenumber,
        'officeroom': value.officeroom,
        'prename': value.prename,
        'registrar': value.registrar,
        'telephonenumber': value.telephonenumber,
        'user': value.user,
    };
}


