/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDoctorinfo,
    EntDoctorinfoFromJSON,
    EntDoctorinfoFromJSONTyped,
    EntDoctorinfoToJSON,
    EntHistorytaking,
    EntHistorytakingFromJSON,
    EntHistorytakingFromJSONTyped,
    EntHistorytakingToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDepartmentEdges
 */
export interface EntDepartmentEdges {
    /**
     * EdgesOfDepartment2doctorinfo holds the value of the EdgesOfDepartment2doctorinfo edge.
     * @type {Array<EntDoctorinfo>}
     * @memberof EntDepartmentEdges
     */
    edgesOfDepartment2doctorinfo?: Array<EntDoctorinfo>;
    /**
     * EdgesOfHistorytaking holds the value of the EdgesOfHistorytaking edge.
     * @type {Array<EntHistorytaking>}
     * @memberof EntDepartmentEdges
     */
    edgesOfHistorytaking?: Array<EntHistorytaking>;
}

export function EntDepartmentEdgesFromJSON(json: any): EntDepartmentEdges {
    return EntDepartmentEdgesFromJSONTyped(json, false);
}

export function EntDepartmentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDepartmentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edgesOfDepartment2doctorinfo': !exists(json, 'EdgesOfDepartment2doctorinfo') ? undefined : ((json['EdgesOfDepartment2doctorinfo'] as Array<any>).map(EntDoctorinfoFromJSON)),
        'edgesOfHistorytaking': !exists(json, 'EdgesOfHistorytaking') ? undefined : ((json['EdgesOfHistorytaking'] as Array<any>).map(EntHistorytakingFromJSON)),
    };
}

export function EntDepartmentEdgesToJSON(value?: EntDepartmentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'EdgesOfDepartment2doctorinfo': value.edgesOfDepartment2doctorinfo === undefined ? undefined : ((value.edgesOfDepartment2doctorinfo as Array<any>).map(EntDoctorinfoToJSON)),
        'EdgesOfHistorytaking': value.edgesOfHistorytaking === undefined ? undefined : ((value.edgesOfHistorytaking as Array<any>).map(EntHistorytakingToJSON)),
    };
}


