/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntFinancierEdges,
    EntFinancierEdgesFromJSON,
    EntFinancierEdgesFromJSONTyped,
    EntFinancierEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntFinancier
 */
export interface EntFinancier {
    /**
     * Name holds the value of the "Name" field.
     * @type {string}
     * @memberof EntFinancier
     */
    name?: string;
    /**
     * 
     * @type {EntFinancierEdges}
     * @memberof EntFinancier
     */
    edges?: EntFinancierEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntFinancier
     */
    id?: number;
}

export function EntFinancierFromJSON(json: any): EntFinancier {
    return EntFinancierFromJSONTyped(json, false);
}

export function EntFinancierFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntFinancier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'edges': !exists(json, 'edges') ? undefined : EntFinancierEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntFinancierToJSON(value?: EntFinancier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'edges': EntFinancierEdgesToJSON(value.edges),
        'id': value.id,
    };
}


