/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntOfficeroomEdges,
    EntOfficeroomEdgesFromJSON,
    EntOfficeroomEdgesFromJSONTyped,
    EntOfficeroomEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntOfficeroom
 */
export interface EntOfficeroom {
    /**
     * 
     * @type {EntOfficeroomEdges}
     * @memberof EntOfficeroom
     */
    edges?: EntOfficeroomEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntOfficeroom
     */
    id?: number;
    /**
     * Roomnumber holds the value of the "roomnumber" field.
     * @type {number}
     * @memberof EntOfficeroom
     */
    roomnumber?: number;
}

export function EntOfficeroomFromJSON(json: any): EntOfficeroom {
    return EntOfficeroomFromJSONTyped(json, false);
}

export function EntOfficeroomFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntOfficeroom {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntOfficeroomEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'roomnumber': !exists(json, 'roomnumber') ? undefined : json['roomnumber'],
    };
}

export function EntOfficeroomToJSON(value?: EntOfficeroom | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntOfficeroomEdgesToJSON(value.edges),
        'id': value.id,
        'roomnumber': value.roomnumber,
    };
}


