/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDoctorinfo,
    EntDoctorinfoFromJSON,
    EntDoctorinfoFromJSONTyped,
    EntDoctorinfoToJSON,
    EntPatientrecord,
    EntPatientrecordFromJSON,
    EntPatientrecordFromJSONTyped,
    EntPatientrecordToJSON,
    EntTypetreatment,
    EntTypetreatmentFromJSON,
    EntTypetreatmentFromJSONTyped,
    EntTypetreatmentToJSON,
    EntUnpaybill,
    EntUnpaybillFromJSON,
    EntUnpaybillFromJSONTyped,
    EntUnpaybillToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntTreatmentEdges
 */
export interface EntTreatmentEdges {
    /**
     * 
     * @type {EntDoctorinfo}
     * @memberof EntTreatmentEdges
     */
    doctorinfo?: EntDoctorinfo;
    /**
     * 
     * @type {EntPatientrecord}
     * @memberof EntTreatmentEdges
     */
    patientrecord?: EntPatientrecord;
    /**
     * 
     * @type {EntTypetreatment}
     * @memberof EntTreatmentEdges
     */
    typetreatment?: EntTypetreatment;
    /**
     * 
     * @type {EntUnpaybill}
     * @memberof EntTreatmentEdges
     */
    unpaybills?: EntUnpaybill;
}

export function EntTreatmentEdgesFromJSON(json: any): EntTreatmentEdges {
    return EntTreatmentEdgesFromJSONTyped(json, false);
}

export function EntTreatmentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntTreatmentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doctorinfo': !exists(json, 'doctorinfo') ? undefined : EntDoctorinfoFromJSON(json['doctorinfo']),
        'patientrecord': !exists(json, 'patientrecord') ? undefined : EntPatientrecordFromJSON(json['patientrecord']),
        'typetreatment': !exists(json, 'typetreatment') ? undefined : EntTypetreatmentFromJSON(json['typetreatment']),
        'unpaybills': !exists(json, 'unpaybills') ? undefined : EntUnpaybillFromJSON(json['unpaybills']),
    };
}

export function EntTreatmentEdgesToJSON(value?: EntTreatmentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doctorinfo': EntDoctorinfoToJSON(value.doctorinfo),
        'patientrecord': EntPatientrecordToJSON(value.patientrecord),
        'typetreatment': EntTypetreatmentToJSON(value.typetreatment),
        'unpaybills': EntUnpaybillToJSON(value.unpaybills),
    };
}


