/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDoctor,
    EntDoctorFromJSON,
    EntDoctorFromJSONTyped,
    EntDoctorToJSON,
    EntFinancier,
    EntFinancierFromJSON,
    EntFinancierFromJSONTyped,
    EntFinancierToJSON,
    EntMedicalrecordstaff,
    EntMedicalrecordstaffFromJSON,
    EntMedicalrecordstaffFromJSONTyped,
    EntMedicalrecordstaffToJSON,
    EntNurse,
    EntNurseFromJSON,
    EntNurseFromJSONTyped,
    EntNurseToJSON,
    EntPatientrights,
    EntPatientrightsFromJSON,
    EntPatientrightsFromJSONTyped,
    EntPatientrightsToJSON,
    EntRegistrar,
    EntRegistrarFromJSON,
    EntRegistrarFromJSONTyped,
    EntRegistrarToJSON,
    EntUserstatus,
    EntUserstatusFromJSON,
    EntUserstatusFromJSONTyped,
    EntUserstatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUserEdges
 */
export interface EntUserEdges {
    /**
     * 
     * @type {EntDoctor}
     * @memberof EntUserEdges
     */
    doctor?: EntDoctor;
    /**
     * 
     * @type {EntFinancier}
     * @memberof EntUserEdges
     */
    financier?: EntFinancier;
    /**
     * 
     * @type {EntMedicalrecordstaff}
     * @memberof EntUserEdges
     */
    medicalrecordstaff?: EntMedicalrecordstaff;
    /**
     * 
     * @type {EntNurse}
     * @memberof EntUserEdges
     */
    nurse?: EntNurse;
    /**
     * 
     * @type {EntRegistrar}
     * @memberof EntUserEdges
     */
    user2registrar?: EntRegistrar;
    /**
     * 
     * @type {EntPatientrights}
     * @memberof EntUserEdges
     */
    userPatientrights?: EntPatientrights;
    /**
     * 
     * @type {EntUserstatus}
     * @memberof EntUserEdges
     */
    userstatus?: EntUserstatus;
}

export function EntUserEdgesFromJSON(json: any): EntUserEdges {
    return EntUserEdgesFromJSONTyped(json, false);
}

export function EntUserEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doctor': !exists(json, 'Doctor') ? undefined : EntDoctorFromJSON(json['Doctor']),
        'financier': !exists(json, 'Financier') ? undefined : EntFinancierFromJSON(json['Financier']),
        'medicalrecordstaff': !exists(json, 'Medicalrecordstaff') ? undefined : EntMedicalrecordstaffFromJSON(json['Medicalrecordstaff']),
        'nurse': !exists(json, 'Nurse') ? undefined : EntNurseFromJSON(json['Nurse']),
        'user2registrar': !exists(json, 'User2registrar') ? undefined : EntRegistrarFromJSON(json['User2registrar']),
        'userPatientrights': !exists(json, 'UserPatientrights') ? undefined : EntPatientrightsFromJSON(json['UserPatientrights']),
        'userstatus': !exists(json, 'Userstatus') ? undefined : EntUserstatusFromJSON(json['Userstatus']),
    };
}

export function EntUserEdgesToJSON(value?: EntUserEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doctor': EntDoctorToJSON(value.doctor),
        'financier': EntFinancierToJSON(value.financier),
        'medicalrecordstaff': EntMedicalrecordstaffToJSON(value.medicalrecordstaff),
        'nurse': EntNurseToJSON(value.nurse),
        'user2registrar': EntRegistrarToJSON(value.user2registrar),
        'userPatientrights': EntPatientrightsToJSON(value.userPatientrights),
        'userstatus': EntUserstatusToJSON(value.userstatus),
    };
}


